# Import Library

In [4]:
import requests
import pandas as pd
from bs4 import BeautifulSoup
import openpyxl

# Scrapping Website CoinMarketCap

In [13]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import openpyxl
def scappe(): # Kamu bisa ubah jadi 'scrape' biar lebih pro :)
    url = 'https://coinmarketcap.com/gainers-losers/'
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'
    }
    
    # PERBAIKAN: Gunakan requests.get, bukan response.get
    try:
        response = requests.get(url, headers=headers)
    except Exception as e:
        print(f"Koneksi gagal: {e}")
        return [], []
    
    if response.status_code != 200:
        print(f'Error: {response.status_code}')
        return [], []

    soup = BeautifulSoup(response.text, 'html.parser')
    
    # PERBAIKAN: Pastikan findAll menemukan tabelnya
    tables = soup.findAll('table', class_='cmc-table')
    
    if len(tables) < 2:
        print("Tabel tidak ditemukan di halaman.")
        return [], []
    
    # PERBAIKAN: Hapus tanda koma di akhir baris ini
    gainers_table = tables[0]
    losers_table = tables[1]
    
    def parse_table(target_table):
        data = []
        rows = target_table.findAll('tr')[1:] # Skip header
        for row in rows:
            cols = row.findAll('td')
            if len(cols) >= 4:
                # Ambil teks koin dan bersihkan
                name = cols[1].text.strip()
                price = cols[2].text.strip()
                change_24h = cols[3].text.strip()
                
                data.append({
                    "Name": name,
                    "Price": price,
                    "24h Change": change_24h
                })
        return data
    
    gainers_data = parse_table(gainers_table)
    losers_data = parse_table(losers_table)

    return gainers_data, losers_data    

# Menjalankan fungsi
gainers, losers = scappe()

# Menampilkan hasil dengan pengecekan data
if gainers or losers:
    print("--- TOP GAINERS ---")
    df_gainers = pd.DataFrame(gainers)
  
    df_gainers_excel = df_gainers.to_excel("gainers.xlsx")
    print(df_gainers.head(10))

    print("\n--- TOP LOSERS ---")
    df_losers = pd.DataFrame(losers)
    df_losers_excel = df_losers.to_excel("losers.xlsx")
    print(df_losers.head(10))
else:
    print("Tidak ada data yang berhasil diambil.")

--- TOP GAINERS ---
                      Name     Price 24h Change
0  Aerodrome Finance95AERO    $0.455     19.48%
1               币安人生99币安人生   $0.3997     14.58%
2            RaveDAO22RAVE    $19.50     14.40%
3           Morpho65MORPHO     $1.98     10.84%
4           Bittensor32TAO   $264.95     10.12%
5                JUST80JST  $0.06636      9.89%
6              Ethena54ENA   $0.1176      9.38%
7              edgeX88EDGE     $1.30      8.46%
8               DeXe57DEXE    $12.15      8.35%
9               Kaspa59KAS   $0.0362      7.93%

--- TOP LOSERS ---
                Name     Price 24h Change
0       siren83SIREN   $0.7009     47.13%
1     Worldcoin60WLD    $0.301      5.55%
2        Chiliz92CHZ  $0.04138      3.93%
3       Toncoin30TON     $1.42      1.48%
4      Filecoin68FIL     $1.00      1.14%
5           TRON8TRX   $0.3253      0.22%
6  UNUS SED LEO12LEO    $10.13      0.15%

C:\Users\Asus\AppData\Local\Temp\ipykernel_23408\2154096.py:25: DeprecationWarning: Call to deprecated method findAll. (Replaced by find_all) -- Deprecated since version 4.0.0.
  tables = soup.findAll('table', class_='cmc-table')
C:\Users\Asus\AppData\Local\Temp\ipykernel_23408\2154096.py:37: DeprecationWarning: Call to deprecated method findAll. (Replaced by find_all) -- Deprecated since version 4.0.0.
  rows = target_table.findAll('tr')[1:] # Skip header
C:\Users\Asus\AppData\Local\Temp\ipykernel_23408\2154096.py:39: DeprecationWarning: Call to deprecated method findAll. (Replaced by find_all) -- Deprecated since version 4.0.0.
  cols = row.findAll('td')

# DataFrame Gainners Coin

In [16]:
gainners = pd.read_excel("gainers.xlsx")
dataframe_gainners = pd.DataFrame(gainners)
dataframe_gainners.head(10)

   Unnamed: 0                     Name     Price 24h Change
0           0  Aerodrome Finance95AERO    $0.455     19.48%
1           1               币安人生99币安人生   $0.3997     14.58%
2           2            RaveDAO22RAVE    $19.50     14.40%
3           3           Morpho65MORPHO     $1.98     10.84%
4           4           Bittensor32TAO   $264.95     10.12%
5           5                JUST80JST  $0.06636      9.89%
6           6              Ethena54ENA   $0.1176      9.38%
7           7              edgeX88EDGE     $1.30      8.46%
8           8               DeXe57DEXE    $12.15      8.35%
9           9               Kaspa59KAS   $0.0362      7.93%

# DataFrame Lossers Coin

In [17]:
loserss = pd.read_excel("losers.xlsx")
dataframe_losers = pd.DataFrame(loserss)
dataframe_losers.head(10)

   Unnamed: 0               Name     Price 24h Change
0           0       siren83SIREN   $0.7009     47.13%
1           1     Worldcoin60WLD    $0.301      5.55%
2           2        Chiliz92CHZ  $0.04138      3.93%
3           3       Toncoin30TON     $1.42      1.48%
4           4      Filecoin68FIL     $1.00      1.14%
5           5           TRON8TRX   $0.3253      0.22%
6           6  UNUS SED LEO12LEO    $10.13      0.15%

# Check Missing Value