# Import Library

In [4]:
import requests
import pandas as pd
from bs4 import BeautifulSoup
import openpyxl

# Scrapping Website CoinMarketCap

In [21]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import openpyxl
def scappe(): 
    url = 'https://coinmarketcap.com/gainers-losers/'
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'
    }
    

    try:
        response = requests.get(url, headers=headers)
    except Exception as e:
        print(f"Koneksi gagal: {e}")
        return [], []
    
    if response.status_code != 200:
        print(f'Error: {response.status_code}')
        return [], []

    soup = BeautifulSoup(response.text, 'html.parser')
    
    tables = soup.findAll('table', class_='cmc-table')
    
    if len(tables) < 2:
        print("Tabel tidak ditemukan di halaman.")
        return [], []
    
    gainers_table = tables[0]
    losers_table = tables[1]
    
    def parse_table(target_table):
        data = []
        rows = target_table.findAll('tr')[1:]
        for row in rows:
            cols = row.findAll('td')
            if len(cols) >= 4:
                # Ambil teks koin dan bersihkan
                name = cols[1].text.strip()
                price = cols[2].text.strip()
                change_24h = cols[3].text.strip()
                volume_24h = cols[4].text.strip()
                
                data.append({
                    "Name": name,
                    "Price": price,
                    "24h Change": change_24h,
                    "Volume(24h)": volume_24h
                    
                })
        return data
    
    gainers_data = parse_table(gainers_table)
    losers_data = parse_table(losers_table)

    return gainers_data, losers_data    


gainers, losers = scappe()

if gainers or losers:
    print("--- TOP GAINERS ---")
    df_gainers = pd.DataFrame(gainers)
  
    df_gainers_excel = df_gainers.to_excel("gainers.xlsx")
    print(df_gainers.head(10))

    print("\n--- TOP LOSERS ---")
    df_losers = pd.DataFrame(losers)
    df_losers_excel = df_losers.to_excel("losers.xlsx")
    print(df_losers.head(10))
else:
    print("Tidak ada data yang berhasil diambil.")

--- TOP GAINERS ---
                      Name     Price 24h Change   Volume(24h)
0            RaveDAO22RAVE    $20.45     21.92%  $263,640,007
1  Aerodrome Finance95AERO   $0.4565     19.90%   $45,662,766
2               币安人生99币安人生   $0.3973     14.63%  $140,503,809
3           Morpho65MORPHO     $1.98     11.02%   $27,249,916
4           Bittensor32TAO   $266.07     10.62%  $402,912,178
5              Ethena54ENA   $0.1175     10.08%  $181,482,046
6                JUST80JST  $0.06615      9.29%   $55,807,221
7               DeXe57DEXE    $12.16      8.80%   $22,591,721
8              edgeX88EDGE     $1.30      8.11%  $163,839,829
9               Kaspa59KAS   $0.0362      7.99%   $36,667,482

--- TOP LOSERS ---
                Name     Price 24h Change   Volume(24h)
0       siren83SIREN   $0.6968     48.06%  $285,903,398
1     Worldcoin60WLD   $0.3011      5.25%  $217,787,632
2        Chiliz92CHZ  $0.04133      3.94%   $74,179,937
3       Toncoin30TON     $1.41      1.51%  $160,420,045
4      Filecoin68FIL   $0.9999      1.21%  $182,874,048
5           TRON8TRX   $0.3253      0.27%  $793,091,315
6  UNUS SED LEO12LEO    $10.13      0.18%      $546,482

C:\Users\Asus\AppData\Local\Temp\ipykernel_23408\2955714360.py:24: DeprecationWarning: Call to deprecated method findAll. (Replaced by find_all) -- Deprecated since version 4.0.0.
  tables = soup.findAll('table', class_='cmc-table')
C:\Users\Asus\AppData\Local\Temp\ipykernel_23408\2955714360.py:35: DeprecationWarning: Call to deprecated method findAll. (Replaced by find_all) -- Deprecated since version 4.0.0.
  rows = target_table.findAll('tr')[1:]
C:\Users\Asus\AppData\Local\Temp\ipykernel_23408\2955714360.py:37: DeprecationWarning: Call to deprecated method findAll. (Replaced by find_all) -- Deprecated since version 4.0.0.
  cols = row.findAll('td')

# DataFrame Gainners Coin

In [22]:
gainners = pd.read_excel("gainers.xlsx")
dataframe_gainners = pd.DataFrame(gainners)
dataframe_gainners.head(10)

   Unnamed: 0                     Name     Price 24h Change   Volume(24h)
0           0            RaveDAO22RAVE    $20.45     21.92%  $263,640,007
1           1  Aerodrome Finance95AERO   $0.4565     19.90%   $45,662,766
2           2               币安人生99币安人生   $0.3973     14.63%  $140,503,809
3           3           Morpho65MORPHO     $1.98     11.02%   $27,249,916
4           4           Bittensor32TAO   $266.07     10.62%  $402,912,178
5           5              Ethena54ENA   $0.1175     10.08%  $181,482,046
6           6                JUST80JST  $0.06615      9.29%   $55,807,221
7           7               DeXe57DEXE    $12.16      8.80%   $22,591,721
8           8              edgeX88EDGE     $1.30      8.11%  $163,839,829
9           9               Kaspa59KAS   $0.0362      7.99%   $36,667,482

# DataFrame Lossers Coin

In [23]:
loserss = pd.read_excel("losers.xlsx")
dataframe_losers = pd.DataFrame(loserss)
dataframe_losers.head(10)

   Unnamed: 0               Name     Price 24h Change   Volume(24h)
0           0       siren83SIREN   $0.6968     48.06%  $285,903,398
1           1     Worldcoin60WLD   $0.3011      5.25%  $217,787,632
2           2        Chiliz92CHZ  $0.04133      3.94%   $74,179,937
3           3       Toncoin30TON     $1.41      1.51%  $160,420,045
4           4      Filecoin68FIL   $0.9999      1.21%  $182,874,048
5           5           TRON8TRX   $0.3253      0.27%  $793,091,315
6           6  UNUS SED LEO12LEO    $10.13      0.18%      $546,482

# Check Missing Value Gainners

In [24]:
df_gainers.isnull().sum()

Name           0
Price          0
24h Change     0
Volume(24h)    0
dtype: int64

# Check Missing Value Lossers

In [25]:
df_losers.isnull().sum()

Name           0
Price          0
24h Change     0
Volume(24h)    0
dtype: int64