# Import Library

In [1]:
import requests
import pandas as pd
from bs4 import BeautifulSoup
import openpyxl

# Scrapping Website CoinMarketCap

In [2]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import openpyxl
def scappe(): 
    url = 'https://coinmarketcap.com/gainers-losers/'
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'
    }
    

    try:
        response = requests.get(url, headers=headers)
    except Exception as e:
        print(f"Koneksi gagal: {e}")
        return [], []
    
    if response.status_code != 200:
        print(f'Error: {response.status_code}')
        return [], []

    soup = BeautifulSoup(response.text, 'html.parser')
    
    tables = soup.findAll('table', class_='cmc-table')
    
    if len(tables) < 2:
        print("Tabel tidak ditemukan di halaman.")
        return [], []
    
    gainers_table = tables[0]
    losers_table = tables[1]
    
    def parse_table(target_table):
        data = []
        rows = target_table.findAll('tr')[1:]
        for row in rows:
            cols = row.findAll('td')
            if len(cols) >= 4:
                # Ambil teks koin dan bersihkan
                name = cols[1].text.strip()
                price = cols[2].text.strip()
                change_24h = cols[3].text.strip()
                volume_24h = cols[4].text.strip()
                
                data.append({
                    "Name": name,
                    "Price": price,
                    "24h Change": change_24h,
                    "Volume(24h)": volume_24h
                    
                })
        return data
    
    gainers_data = parse_table(gainers_table)
    losers_data = parse_table(losers_table)

    return gainers_data, losers_data    


gainers, losers = scappe()

if gainers or losers:
    print("--- TOP GAINERS ---")
    df_gainers = pd.DataFrame(gainers)
  
    df_gainers_excel = df_gainers.to_excel("gainers.xlsx")
    print(df_gainers.head(10))

    print("\n--- TOP LOSERS ---")
    df_losers = pd.DataFrame(losers)
    df_losers_excel = df_losers.to_excel("losers.xlsx")
    print(df_losers.head(10))
else:
    print("Tidak ada data yang berhasil diambil.")

C:\Users\Asus\AppData\Local\Temp\ipykernel_19428\2955714360.py:24: DeprecationWarning: Call to deprecated method findAll. (Replaced by find_all) -- Deprecated since version 4.0.0.
  tables = soup.findAll('table', class_='cmc-table')
C:\Users\Asus\AppData\Local\Temp\ipykernel_19428\2955714360.py:35: DeprecationWarning: Call to deprecated method findAll. (Replaced by find_all) -- Deprecated since version 4.0.0.
  rows = target_table.findAll('tr')[1:]
C:\Users\Asus\AppData\Local\Temp\ipykernel_19428\2955714360.py:37: DeprecationWarning: Call to deprecated method findAll. (Replaced by find_all) -- Deprecated since version 4.0.0.
  cols = row.findAll('td')

--- TOP GAINERS ---
                      Name     Price 24h Change   Volume(24h)
0            RaveDAO21RAVE    $20.91     27.46%  $274,717,861
1              Ethena54ENA   $0.1282     14.50%  $215,822,861
2  Aerodrome Finance98AERO   $0.4397     12.13%   $55,549,454
3               DeXe55DEXE    $12.29     11.19%   $23,119,099
4              edgeX86EDGE     $1.35     10.39%  $165,522,350
5        Venice Token93VVV     $9.34      8.94%   $21,763,205
6           Morpho67MORPHO     $1.95      8.58%   $28,951,998
7           Bittensor32TAO   $261.94      8.39%  $415,100,954
8              币安人生100币安人生   $0.3666      7.67%  $143,972,828
9                JUST79JST  $0.06753      7.54%   $51,374,400

--- TOP LOSERS ---
                Name      Price 24h Change   Volume(24h)
0       siren88SIREN    $0.6378     59.54%  $255,520,180
1     Worldcoin62WLD    $0.2862      9.43%  $255,173,683
2        Chiliz92CHZ   $0.04148      3.12%   $69,786,630
3  PancakeSwap82CAKE      $1.59      2.49%   $66,523,897
4         Zcash19ZEC    $332.22      2.37%  $456,061,631
5         Bonk78BONK  $0.056534      1.72%  $123,593,913
6         Dash87DASH     $37.11      1.32%  $100,221,661
7       Toncoin30TON      $1.40      1.21%  $164,278,856
8     LayerZero75ZRO      $1.96      0.32%   $46,213,647
9  UNUS SED LEO12LEO     $10.13      0.19%      $546,009

# DataFrame Gainners Coin

In [3]:
gainners = pd.read_excel("gainers.xlsx")
dataframe_gainners = pd.DataFrame(gainners)
dataframe_gainners.head(10)

   Unnamed: 0                     Name     Price 24h Change   Volume(24h)
0           0            RaveDAO21RAVE    $20.91     27.46%  $274,717,861
1           1              Ethena54ENA   $0.1282     14.50%  $215,822,861
2           2  Aerodrome Finance98AERO   $0.4397     12.13%   $55,549,454
3           3               DeXe55DEXE    $12.29     11.19%   $23,119,099
4           4              edgeX86EDGE     $1.35     10.39%  $165,522,350
5           5        Venice Token93VVV     $9.34      8.94%   $21,763,205
6           6           Morpho67MORPHO     $1.95      8.58%   $28,951,998
7           7           Bittensor32TAO   $261.94      8.39%  $415,100,954
8           8              币安人生100币安人生   $0.3666      7.67%  $143,972,828
9           9                JUST79JST  $0.06753      7.54%   $51,374,400

# DataFrame Lossers Coin

In [4]:
loserss = pd.read_excel("losers.xlsx")
dataframe_losers = pd.DataFrame(loserss)
dataframe_losers.head(10)

   Unnamed: 0               Name      Price 24h Change   Volume(24h)
0           0       siren88SIREN    $0.6378     59.54%  $255,520,180
1           1     Worldcoin62WLD    $0.2862      9.43%  $255,173,683
2           2        Chiliz92CHZ   $0.04148      3.12%   $69,786,630
3           3  PancakeSwap82CAKE      $1.59      2.49%   $66,523,897
4           4         Zcash19ZEC    $332.22      2.37%  $456,061,631
5           5         Bonk78BONK  $0.056534      1.72%  $123,593,913
6           6         Dash87DASH     $37.11      1.32%  $100,221,661
7           7       Toncoin30TON      $1.40      1.21%  $164,278,856
8           8     LayerZero75ZRO      $1.96      0.32%   $46,213,647
9           9  UNUS SED LEO12LEO     $10.13      0.19%      $546,009

# Check Missing Value Gainners

In [5]:
df_gainers.isnull().sum()

Name           0
Price          0
24h Change     0
Volume(24h)    0
dtype: int64

# Check Missing Value Lossers

In [6]:
df_losers.isnull().sum()

Name           0
Price          0
24h Change     0
Volume(24h)    0
dtype: int64

# Data Cleaning Gainners

In [7]:
df_gainers['Volume(24h)'] = df_gainers['Volume(24h)'].str.replace('$', '').str.replace(',', '').astype(float)
df_gainers['Price'] = df_gainers['Price'].str.replace('$', '').str.replace(',', '').astype(float)
df_gainers['24h Change'] = df_gainers['24h Change'].str.replace('%', '').astype(float)      


df_gainers

                          Name         Price  24h Change   Volume(24h)
0                RaveDAO21RAVE     20.910000       27.46  2.747179e+08
1                  Ethena54ENA      0.128200       14.50  2.158229e+08
2      Aerodrome Finance98AERO      0.439700       12.13  5.554945e+07
3                   DeXe55DEXE     12.290000       11.19  2.311910e+07
4                  edgeX86EDGE      1.350000       10.39  1.655224e+08
5            Venice Token93VVV      9.340000        8.94  2.176320e+07
6               Morpho67MORPHO      1.950000        8.58  2.895200e+07
7               Bittensor32TAO    261.940000        8.39  4.151010e+08
8                  币安人生100币安人生      0.366600        7.67  1.439728e+08
9                    JUST79JST      0.067530        7.54  5.137440e+07
10             ether.fi90ETHFI      0.521700        7.49  5.033290e+07
11               Celestia99TIA      0.413500        6.09  1.130553e+08
12                 MemeCore22M      3.830000        5.43  1.884878e+07
13                  Kaspa59KAS      0.035650        5.24  3.773110e+07
14                Jupiter72JUP      0.186500        4.61  4.670693e+07
15               Arbitrum66ARB      0.133100        4.23  2.127228e+08
16                  Quant61QNT     77.840000        4.07  1.371979e+07
17                Stellar18XLM      0.173400        3.88  1.649857e+08
18                      Pi41PI      0.180100        3.80  3.214332e+07
19                Ethereum2ETH   2420.950000        3.33  2.611756e+10
20  Virtuals Protocol83VIRTUAL      0.766900        3.28  1.310523e+08
21               GateToken64GT      7.310000        3.10  3.271970e+06
22                    Sky42SKY      0.078880        3.07  1.846949e+07
23                 Bitcoin1BTC  77201.150000        3.05  5.502031e+10
24                  Nexo77NEXO      0.927900        2.93  1.022596e+07
25                  Flare69FLR      0.008414        2.82  5.171299e+06
26                  Aave44AAVE    117.570000        2.66  4.956402e+08
27                Uniswap39UNI      3.510000        2.52  2.676096e+08
28                  Tezos95XTZ      0.383100        2.51  1.549664e+07
29                     XRP4XRP      1.480000        2.51  4.502103e+09

# Data Cleaning Lossers

In [ ]:
df_losers['Price'] = df_losers['Price'].str.replace('$', '').str.replace(',', '').astype(float)
df_losers['24h Change'] = df_losers['24h Change'].str.replace('%', '').astype(float)
df_losers['Volume(24h)'] = df_losers['Volume(24h)'].str.replace('$', '').str.replace(',', '').astype(float)

df_losers

                             Name       Price  24h Change  Volume(24h)
0                    siren88SIREN    0.637800       59.54  255520180.0
1                  Worldcoin62WLD    0.286200        9.43  255173683.0
2                     Chiliz92CHZ    0.041480        3.12   69786630.0
3               PancakeSwap82CAKE    1.590000        2.49   66523897.0
4                      Zcash19ZEC  332.220000        2.37  456061631.0
5                      Bonk78BONK    0.056534        1.72  123593913.0
6                      Dash87DASH   37.110000        1.32  100221661.0
7                    Toncoin30TON    1.400000        1.21  164278856.0
8                  LayerZero75ZRO    1.960000        0.32   46213647.0
9               UNUS SED LEO12LEO   10.130000        0.19     546009.0
10                Avalanche24AVAX    9.780000        0.16  433564827.0
11               XDC Network74XDC    0.031350        0.10   24754028.0
12                 Algorand57ALGO    0.112800        0.08   65898142.0
13  World Liberty Financial34WLFI    0.082220        0.03  109241378.0
14                 Pump.fun71PUMP    0.002030        0.02   92523190.0

# Check Outlier Gainners

In [ ]:
Q1 = df_gainers['Price'].quantile(0.25)
Q3 = df_gainers['Price'].quantile(0.75)
IQR = Q1 - Q3

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

qutlier_iqr = df_gainers[
    (df_gainers['Price'] < lower) | (df_gainers['Price'] > upper)
]

print('Jumlah outlier dari gainers: ', len(qutlier_iqr))